### ISSUE TITLE
Could a port MarkovJunior to JavaScript?

### ISSUE THREAD

**Issue by aseaday** [mxgmn/MarkovJunior#10]
Hi, I appreciated your work very much. And I am interested in porting it to javascript and canvas which could run on a web browser.
Of course, I would also keep the original repo and license in the port version.

**Comment by ryceg** [comment]
@aseaday are you asking if you would be allowed to? MarkovJunior is licensed as MIT, so you are free to do so- and if you do, please let me know, as I'd love to contribute.

**Comment by mxgmn** [comment]
Of course, port away! Ping me when you do, I'll link it from the README.

**Comment by aseaday** [comment]
Thanks for your acceptance, I am working on porting work already.

**Comment by filharvey** [comment]
Nice let me know when you are close, I'm definitely interested in this, and was considering it.

**Comment by ryceg** [comment]
@filharvey @aseaday has already started on it- https://github.com/aseaday/MarkovJunior.js

**Comment by aseaday** [comment]
Hey guys, I finished a very basic [demo](https://markov-junior-js.vercel.app/) which only support OneNode and Branch Node. But the majority of backbone is completed.  
The future work would be adding more features and something more interesting for application or promotion of this job. I think it is a good start.

**Comment by mxgmn** [comment]
I linked it from the README. The thing that I'm missing the most is the ability to browse existing examples like in the [other port](https://github.com/Yuu6883/MarkovJuniorWeb).
