### ISSUE TITLE
How to run on Linux

### ISSUE THREAD

**Issue by gabrielelibardi** [mxgmn/MarkovJunior#12]
I run `dotnet run --configuration Release MarkovJunior.csproj` but nothing happens, what do display the GUI?

**Comment by mxgmn** [comment]
Nothing at all, no error message?

**Comment by gabrielelibardi** [comment]
Right, nothing, no error message. It takes maybe a second to run so it is doing something..

**Comment by mxgmn** [comment]
Does it create the `output` folder?

**Comment by gabrielelibardi** [comment]
No

**Comment by mxgmn** [comment]
What happens if you try to build a [hello world](https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/intro) C# program?

**Comment by gabrielelibardi** [comment]
The hello world example form your link seems to work fine.

**Comment by gabrielelibardi** [comment]
Which .NET core version did you use?

**Comment by mxgmn** [comment]
It's probably the `System.Drawing` thing again, because what else could it be, it just doesn't print the error message for some reason. Try the solutions in [this comment](https://github.com/mxgmn/MarkovJunior/issues/9#issuecomment-1145817678), try first to build with net5.0.

**Comment by gabrielelibardi** [comment]
Actually the problem was that I had installed .NET using snap which apparently has problems [link](https://www.reddit.com/r/dotnet/comments/qrlajf/dotnet_run_command_not_working_on_linux_with_net_6/)  I reinstalled from the official site following [this](https://tecadmin.net/how-to-install-net-core-on-ubuntu-20-04/) and it now works (throws some other error but the app is running and it creates the `/output `dir).

**Comment by MCSH** [comment]
This is the entire log I get when running:

```
Apartemazements > P = 16
CONTRADICTION on try 0 with 142 observations
wfc found a good seed 1643779998 on try 1 with 158 observations
DONE
wfc found a good seed 376360877 on try 0 with 155 observations
DONE
CONTRADICTION on try 0 with 149 observations
CONTRADICTION on try 1 with 124 observations
wfc found a good seed 1346509966 on try 2 with 154 observations
DONE
CONTRADICTION on try 0 with 151 observations
wfc found a good seed 1667801283 on try 1 with 143 observations
DONE
Apartemazements > P = 16
CONTRADICTION on try 0 with 134 observations
CONTRADICTION on try 1 with 101 observations
CONTRADICTION on try 2 with 116 observations
wfc found a good seed 1814048741 on try 3 with 154 observations
Unhandled exception. System.TypeInitializationException: The type initializer for 'GUI' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GUI..cctor() in /home/sajjad/src/git/MarkovJunior/source/GUI.cs:line 30
   --- End of inner exception stack trace ---
   at GUI.Draw(String name, Branch root, Branch current, Int32[] bitmap, Int32 WIDTH, Int32 HEIGHT, Dictionary`2 palette)
   at Program.Main() in /home/sajjad/src/git/MarkovJunior/source/Program.cs:line 67
```

**Comment by mxgmn** [comment]
@MCSH See #9
