### ISSUE TITLE
Customizability of models?

### ISSUE THREAD

**Issue by jeekca** [mxgmn/MarkovJunior#14]
Hey guys,

Amazing tool. I generated several CarmaTowers and I was greatly impressed with the results.

That said, I've read most of the documentation, and yet I'm still not able to wrap my head around the process of creating a custom model with its own rules/constraints/MagicaVoxel pieces. In other words, I'm looking to generate my own CarmaTower-type buildings, but the XML of CarmaTower.xml is a tad cryptic at the moment, especially without any documentation.

I know this was just released, so please tell me if it's too early to attempt such a thing.

Thanks a ton!

**Comment by mxgmn** [comment]
CarmaTower is one of the most advanced models here. I recommend to start with models mentioned in the README and see how they look in .xml form: Basic -> Growth -> MazeGrowth -> ... -> NystromDungeon -> .... And then try to modify them and see what happens.

A few tips. In `models.xml`:

1. Set `gif="True"` to see all steps the interpreter is making.
2. Set `gui="300"` to see which nodes are active on each step.

**Comment by jeekca** [comment]
Ah! Duly noted. Thank you so much @mxgmn!
