### ISSUE TITLE
odd results from one of the generated sea villas

### ISSUE THREAD

**Issue by Aeva** [mxgmn/MarkovJunior#2]
![image](https://user-images.githubusercontent.com/768449/171549351-8ad44b53-48f8-4357-97e0-a84322086af7.png)
The file name was `SeaVilla_1058505240.vox`, if that tells you anything useful.  Idk if this is a bug or not, but I figured you might be interested either way.

**Comment by Aeva** [comment]
another view of the same file ![image](https://user-images.githubusercontent.com/768449/171549650-3a4b45d9-1c32-4d17-8de3-482a881b008c.png)

**Comment by mxgmn** [comment]
Yeah, SeaVilla generator can fail sometimes. Ideally runs like this should be filtered out automatically, but I haven't done this yet.
