### ISSUE TITLE
Build failed with step as 'How to build' section

### ISSUE THREAD

**Issue by abeq** [mxgmn/MarkovJunior#44]
I have tried to build with `dotnet run --configuration Release MarkovJunior.csproj`, but build failed with error message:
```
C:\Users\user\MarkovJunior\MarkovJunior.csproj : error NU1100: 'net6.0' に対する 'System.Drawing.Common (>= 4.5.1)' を解決できません。
```
It is Japanese,  means "Could not resolve System,Drawing.Common for net 6.0".
Please correct if document is wrong.

**Comment by mxgmn** [comment]
Should build now.
