### ISSUE TITLE
The intro page does not explain how MJ start running when there's no rule matched at the first place 

### ISSUE THREAD

**Issue by markringo** [mxgmn/MarkovJunior#47]
Take the simple [Growth](https://github.com/mxgmn/MarkovJunior/blob/main/models/Growth.xml) model for example, when you start the MJ it's all Bs on the grid so there's no "WB" to start with, so in what mechanism does MJ put a W in center (or via any other way) so that a "WB" can be matched therefore Growth can actually "grow"?

I guess the property "origin=True" might be the trick, but after a rough browsing I somehow can't find the right source (and it seems to me that it could be more "configurable" than just a boolean) to this design and I think this needs some serious explanation at the first section of the intro.

**Comment by mxgmn** [comment]
It's indeed the origin, I explain this in [syntax overview](https://github.com/mxgmn/MarkovJunior/blob/main/syntax.md):

> If origin is set True, the interpreter creates a pixel at the center of the grid with the value equal to the second value in values. For example, values="YRBAN" origin="True" creates a yellow screen with a red dot in the center.

**Comment by markringo** [comment]
> It's indeed the origin, I explain this in [syntax overview](https://github.com/mxgmn/MarkovJunior/blob/main/syntax.md):
> 
Oh I missed it, thanks.
