### ISSUE TITLE
Document Probability Attribute

### ISSUE THREAD

**Issue by dmadisetti** [mxgmn/MarkovJunior#48]
Hi,

Thanks for your recent effort in documenting this project. I have an intern tinkering with this (@GraceMagnyFokam) and we're getting some unexpected behavior. For instance

```
<one p="0.1"> 
```

does not seem to work. In addition `<prl p="0.1" steps="1">` seems to fill the whole screen? I'm sorry I am passing on this information secondhand, but hoping you had some insight.

Thanks!
Dylan

**Comment by mxgmn** [comment]
Hi! `p` attribute in `one` nodes doesn't do anything, it's only for `prl` nodes. I can easily add it to `one` nodes, but I have never encountered an example where I would want to do that. If you share such an example, I may add this feature.

`<prl values="BW" in="B" out="W" p="0.1"/>` indeed makes most of the screen white, because it applies this rule many times. If you want only 10% white, you need `<prl values="BW" in="B" out="W" p="0.1" steps="1"/>`.

**Comment by FarzadBT** [comment]
Sorry for necrobumping this, discovered this issue while I was working on a level generator, so I hope to at least provide an example where I'd like to use the `p` attribute in a `one` node.

The level generator works as such that we place a "spawn", place an "uncompleted goal", set waypoints, and then path from spawn to goal using constraints and inference.
Here's one level being generated
![ezgif-1-be8cc77201](https://github.com/user-attachments/assets/027fcfe9-aaf9-45ee-b532-4c60a49d37e9)

For this example I care about when the waypoints are set.
![ezgif-1-bdc28f537f](https://github.com/user-attachments/assets/e6b6e224-a6bc-423f-b4ad-659c2c8fba13)
This is done with `<one in="A" out="Y" steps="3"/>`.

Now consider that I would want to adjust the complexity of this stage through the number of waypoints, at minimum I would want one waypoint set, at maximum I would want 3+ (depending on the size of the stage). This can sort of be done with something like a `<prl p=0.1 steps=1 />` node, but then I lose out on controlling the maximum and minimum number of waypoints. At a very slim chance `prl` will either make all grAy tiles Yellow, or none of them.

That's where I tried the following (and discovered that it didn't work):
```
<one in="A" out="Y" steps="1"/>
<one in="A" out="Y" steps="2" p="0.5"/>
```
So the thought here was that, at minimum we get 1 waypoint set. And then there's a _chance_ for the level to become more complicated with more set waypoints.
