### ISSUE TITLE
Are there command line arguments or a UI?

### ISSUE THREAD

**Issue by arduino5144** [mxgmn/MarkovJunior#49]
I want to visualize it as it runs and be able to choose which model to run. Is there an option for that?

**Comment by kaya3** [comment]
Currently there isn't; the way to run a particular model is to edit the `models.xml` file and comment out all of the ones you don't want to run. Command-line arguments would be useful though.

**Comment by mxgmn** [comment]
It's possible that I'll publish an interactive graphical version later. Meanwhile, you can play with @Yuu6883's [web version](https://yuu6883.github.io/MarkovJuniorWeb/). Command line arguments aren't planned.
