### ISSUE TITLE
Some small optimizations suggestion

### ISSUE THREAD

**Issue by purebill** [mxgmn/MarkovJunior#5]
I can't help to suggest some small optimization suggestions I didn't dive deep into the code to see how these methods are used and maybe this is some unneeded optimization, but just in case :)

* For [Power](https://github.com/mxgmn/MarkovJunior/blob/main/source/Helper.cs#L34) you can use [Exponentiation by squaring](https://en.wikipedia.org/wiki/Exponentiation_by_squaring).
* For [weighted Random](https://github.com/mxgmn/MarkovJunior/blob/main/source/Helper.cs#L93) you can consider using ideas from [this article](https://www.keithschwarz.com/darts-dice-coins/).

**Comment by tommyettinger** [comment]
I'm definitely a fan of Vose' Alias Method, from the Darts, Dice and Coins article. I've also implemented it in C# (also MIT-licensed) if anyone wants it: https://github.com/tommyettinger/ShaiRandom/blob/main/ShaiRandom/Collections/ProbabilityTable.cs 

The question with Vose' Alias Method is mostly if weighted random sampling is done enough times, from a large enough pool of items, to matter in terms of performance. It isn't much more complicated, but if the set of weights changes very often, then it can be slower than the existing code (O(n) to build the table, so if the table is frequently re-built, then the O(1) performance of each query might not help enough).

Also, I think FirstNonZeroPosition is nearly equivalent to this .NET Core and higher method: https://docs.microsoft.com/en-us/dotnet/api/system.numerics.bitoperations.trailingzerocount?view=net-6.0#system-numerics-bitoperations-trailingzerocount(system-int32)

**Comment by mxgmn** [comment]
Thanks @tommyettinger, I used `TrailingZeroCount()`. The article is great, but `Power()` and weighted random are called so rarely that optimizing them wouldn't be worth the increase in complexity.
