### ISSUE TITLE
Constraint

### ISSUE THREAD

**Issue by DushesA7** [mxgmn/MarkovJunior#61]
Hello. I can't understand ho to add some constraint for WFC. I want to generate river between two points, that points should be declared by me before start of programm.

**Comment by mxgmn** [comment]
Hi Andrey! I just added the [TilePath](https://github.com/mxgmn/MarkovJunior/blob/main/models/TilePath.xml) example - it generates a river between 2 points using WFC. I described the idea behind this method in [this thread](https://twitter.com/ExUtumno/status/1024314661951467521).
