### ISSUE TITLE
Unhandled System.TypeInitializationException

### ISSUE THREAD

**Issue by smokracek** [mxgmn/MarkovJunior#9]
Cloned the repo to do some playing around on my own and got an exception when I ran the project for the first time with `dotnet run --configuration Release MarkovJunior.csproj`.

Here's the full output:
```
$ dotnet run --configuration Release MarkovJunior.csproj
Apartemazements > P = 16
CONTRADICTION on try 0 with 123 observations
CONTRADICTION on try 1 with 139 observations
CONTRADICTION on try 2 with 126 observations
wfc found a good seed 53119890 on try 3 with 141 observations
DONE
wfc found a good seed 34514102 on try 0 with 157 observations
DONE
wfc found a good seed 780037807 on try 0 with 156 observations
DONE
CONTRADICTION on try 0 with 159 observations
CONTRADICTION on try 1 with 111 observations
wfc found a good seed 1719455730 on try 2 with 168 observations
DONE
Apartemazements > P = 16
wfc found a good seed 1290867910 on try 0 with 156 observations
Unhandled exception. System.TypeInitializationException: The type initializer for 'GUI' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GUI..cctor() in /Users/sammokracek/Desktop/MarkovJunior/source/GUI.cs:line 30
   --- End of inner exception stack trace ---
   at GUI.Draw(String name, Branch root, Branch current, Int32[] bitmap, Int32 WIDTH, Int32 HEIGHT, Dictionary`2 palette)
   at Program.Main() in /Users/sammokracek/Desktop/MarkovJunior/source/Program.cs:line 67
```

Seems like this is some sort of issue with the GUI not initializing correctly. Not too knowlegable in .NET, C#, or this project so if there's something simple I'm missing I apologize.

System info:
MacBook Air 2018 (Intel)
MacOs 12.3.1
Fresh .NET 6.0.3 install

**Comment by jminor** [comment]
Try removing this line from `models.xml`:

` <model name="Apartemazements" size="8" d="3" iso="True" pixelsize="6" gui="150"/>`

**Comment by mxgmn** [comment]
This happens on Mac and Linux because of the System.Drawing dependency. I'll remove this dependency when I have time. The quick fixes are either:
* Remove all `gui` attributes from `models.xml`
* Change "net6.0" to "net5.0" in MarkovJunior.csproj and build with net5.0.
* Install `libgdiplus`. On Mac: `$ brew install dotnet mono-libgdiplus`
* Apply [this PR](https://github.com/mxgmn/MarkovJunior/pull/4) in your fork.

**Comment by entangledothers** [comment]
> * Apply [this PR](https://github.com/mxgmn/MarkovJunior/pull/4) in your fork.

Trying on the PR ended up with a new error:` CarmaTower > Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.`. This is one an M1 MBP (OSX 12.3.1) with a fresh .NET 6.0.3 install (for ARM) and libgdiplus installed.

**Comment by mxgmn** [comment]
But with libgdiplus it should work without the PR. Doesn't it?

**Comment by entangledothers** [comment]
I'm afraid not, tried that first. Libgdiplus is installed with brew as per instructions above, when used with this repo (and not the PR), it fails with 'Unhandled exception. System.TypeInitializationException: The type initializer for 'GUI' threw an exception.'. This might be some issue with M1 and dependencies, perhaps?

**Comment by mxgmn** [comment]
The png format turned out to be surprisingly complicated, so I accepted the ImageSharp PR #4. Thank you, Andrew @ahouts ! I'll check out the gif format next, maybe I'll add a built-in gif encoder.
